### PR TITLE
fix  a NSString type-defect

### PR DESCRIPTION
**Pull request by Rm1210**
While I try the Demo on **Lion 10.7.4** and **Xcode 4.6.3 (4H1503)** , the **copy** declared of the tooltip property in `BFIconTabBar.h`  cause the following  problem:

8c3b5678-b20c-4118-ae40-674c652939a9

### CODE REVIEW

**Comment by DrummerB** [comment]
Hi. Are you sure you configured your project properly? Take a look at these questions, maybe they help:
[Program run on iOS 5.1 device can't find SDK with Xcode 4.5](http://stackoverflow.com/questions/12686009/program-run-at-ios5-1-device-cant-find-sdk-at-xcode-4-5)
[What can cause a “Symbol not found: _objc_setProperty_atomic” error when compiling for iOS 5.0?](http://stackoverflow.com/questions/12861345/what-can-cause-a-symbol-not-found-objc-setproperty-atomic-error-when-compili)
I don't quite understand how using strong instead of copy should fix any error like that.

**Comment by Rm1210** [comment]
I am sorry for my carelessness.  I had Google for the problem before I make the Pull Requests. And I  found some answer like your link.  I just think this repository will have absolutely no relationship with some iOS setting. And then I try the **strong**, it just work fine.

Today I found the problem is similar to the iOS problem in your link.

**Comment by DrummerB** [comment]
So you were able to fix it? What was the problem?

**Comment by Rm1210** [comment]
I change the **TARGETS**'s Deployment Target to 10.7 and left the **PROJECT**'s Deployment Target in 10.8.

**Pull request closed without merging**
